export type DocKind = "esquema" | "manual" | "receptor" | "central" | "kit";

export type CatalogDoc = {
  id: string;
  brandId: string;
  title: string;
  model: string;
  kind: DocKind;
  keywords: string[];
  hint: string;
  url?: string;
  synced?: boolean;
};

export const CATALOG: CatalogDoc[] = [
  {
    id: "faac-455d",
    brandId: "faac",
    title: "Central FAAC 455 D",
    model: "455 D",
    kind: "central",
    keywords: ["455d", "455 d", "placa", "central", "batiente"],
    hint: "Esquema de bornes, dip-switch y fotocélulas para batientes 24/230 V.",
  },
  {
    id: "faac-e024s",
    brandId: "faac",
    title: "Central FAAC E024S",
    model: "E024S",
    kind: "central",
    keywords: ["e024s", "e024", "24v", "415", "390"],
    hint: "Central 24 V para 415 L / 390. Encoder y slow-down.",
  },
  {
    id: "faac-740",
    brandId: "faac",
    title: "Motor corredera FAAC 740 / 741",
    model: "740 741",
    kind: "kit",
    keywords: ["740", "741", "corredera", "cremallera"],
    hint: "Manual de instalación 230 V, fin de carrera y central 578 D.",
  },
  {
    id: "faac-844",
    brandId: "faac",
    title: "FAAC 844 ER",
    model: "844",
    kind: "kit",
    keywords: ["844", "er", "industrial"],
    hint: "Corredera industrial. Central 780 D / E045.",
  },
  {
    id: "faac-401mp",
    brandId: "faac",
    title: "FAAC 401 MP / 401 MPS",
    model: "401 MP",
    kind: "central",
    keywords: [
      "401",
      "401mp",
      "401 mp",
      "401mps",
      "401 mps",
      "hidraulico",
      "batiente",
    ],
    hint: "Central 401 MP para operadores hidráulicos 400/401. Esquema de bornes, dip-switch y fotocélulas.",
    url: "https://www.pulldoor.es/wp-content/uploads/2018/09/401_MPS_401MPS_multi.pdf",
  },
  {
    id: "nice-robus",
    brandId: "nice",
    title: "Nice Robus 400 / 600 / 1000",
    model: "Robus",
    kind: "kit",
    keywords: ["robus", "rb400", "rb600", "rb1000", "corredera"],
    hint: "Esquema Moonclever MC424L / MC800.",
  },
  {
    id: "nice-toona",
    brandId: "nice",
    title: "Nice Toona",
    model: "Toona",
    kind: "kit",
    keywords: ["toona", "to4024", "to5024", "batiente"],
    hint: "Actuador hidráulico/electromecánico batiente + MC424.",
  },
  {
    id: "nice-wingo",
    brandId: "nice",
    title: "Nice Wingo",
    model: "Wingo",
    kind: "kit",
    keywords: ["wingo", "wg4000", "wg4024"],
    hint: "Kit batiente residencial. Programación vía O-View.",
  },
  {
    id: "nice-flo",
    brandId: "nice",
    title: "Emisores Nice FLO / FLO R",
    model: "FLO",
    kind: "receptor",
    keywords: ["flo", "flor", "flo2r", "smilo", "oxi"],
    hint: "Codificación, memorización en OXIBD / FLOX2R.",
  },
  {
    id: "came-bx",
    brandId: "came",
    title: "CAME BX / BXV",
    model: "BX",
    kind: "kit",
    keywords: ["bx", "bxv", "bx-74", "bx-78", "zl65", "zl92"],
    hint: "Corredera. Centrales ZL65 / ZL92 / ZLJ24.",
  },
  {
    id: "came-frog",
    brandId: "came",
    title: "CAME Frog",
    model: "Frog",
    kind: "kit",
    keywords: ["frog", "enterrado", "batiente"],
    hint: "Motor enterrado 230/24 V. Esquema ZA3 / ZM3E.",
  },
  {
    id: "came-ati",
    brandId: "came",
    title: "CAME ATI",
    model: "ATI",
    kind: "kit",
    keywords: ["ati", "a3000", "a5000"],
    hint: "Brazo articulado. Central ZA3P / ZL180.",
  },
  {
    id: "bft-deimos",
    brandId: "bft",
    title: "BFT Deimos Ultra",
    model: "Deimos",
    kind: "kit",
    keywords: ["deimos", "ultra bt", "leo", "merak"],
    hint: "Corredera 24 V. Central MERAK / LEO D MA.",
  },
  {
    id: "bft-phobos",
    brandId: "bft",
    title: "BFT Phobos BT",
    model: "Phobos",
    kind: "kit",
    keywords: ["phobos", "batiente", "thalia"],
    hint: "Batiente 24 V. Central THALIA / ALTAIR.",
  },
  {
    id: "bft-icaro",
    brandId: "bft",
    title: "BFT Icaro",
    model: "Icaro",
    kind: "kit",
    keywords: ["icaro", "nv", "leo b cbb"],
    hint: "Corredera 230 V industrial.",
  },
  {
    id: "beninca-bull",
    brandId: "beninca",
    title: "Beninca BULL",
    model: "BULL",
    kind: "kit",
    keywords: ["bull", "bull5", "bull8", "brainy"],
    hint: "Corredera. Central BRAINY 24 / HEADY.",
  },
  {
    id: "beninca-bob",
    brandId: "beninca",
    title: "Beninca BOB / KBOB",
    model: "BOB",
    kind: "kit",
    keywords: ["bob", "kbob", "batiente"],
    hint: "Pistón batiente. Central BRAINY.",
  },
  {
    id: "erreka-lira",
    brandId: "erreka",
    title: "Erreka LIRA / VULCAN",
    model: "LIRA",
    kind: "kit",
    keywords: ["lira", "vulcan", "pulsar", "kuad"],
    hint: "Centrales KUAD / VIVO. Corredera y batiente.",
  },
  {
    id: "v2-city",
    brandId: "v2",
    title: "V2 CITY1 / CITY2",
    model: "CITY",
    kind: "central",
    keywords: ["city", "city1", "city2", "hydra", "calypso"],
    hint: "Centrales 230/24 V. Esquema de bornes y radio WALLY.",
  },
  {
    id: "motorline-kit",
    brandId: "motorline",
    title: "Motorline Professional",
    model: "Professional",
    kind: "kit",
    keywords: ["motorline", "mc2", "mc4", "braço", "deslizante"],
    hint: "Centrales MC2 / MC4, motores corredera y batiente.",
  },
  {
    id: "pujol-winner",
    brandId: "pujol",
    title: "Pujol Winner / Ducati",
    model: "Winner",
    kind: "kit",
    keywords: ["winner", "ducati", "tefer", "pujol"],
    hint: "Motores y cuadros Pujol. Mandos TEFER.",
  },
  {
    id: "clemsa-mutan",
    brandId: "clemsa",
    title: "Clemsa Mutancode",
    model: "Mutancode",
    kind: "receptor",
    keywords: ["mutancode", "mutan", "clemsa", "nero", "rollcode"],
    hint: "Receptores y mandos rolling code. Esquema de relé NA.",
  },
  {
    id: "cdvi-digicode",
    brandId: "cdvi",
    title: "CDVI Digicode",
    model: "Digicode",
    kind: "central",
    keywords: ["digicode", "dga", "dga1030", "teclado", "codigo"],
    hint: "Teclados de código. Esquema de relé, programación y temporización.",
  },
  {
    id: "cdvi-atrium",
    brandId: "cdvi",
    title: "CDVI ATRIUM",
    model: "ATRIUM",
    kind: "central",
    keywords: ["atrium", "a22", "a22k", "control de acceso", "centaur"],
    hint: "Control de acceso ATRIUM / A22. Manual de instalación y software.",
  },
  {
    id: "cdvi-galeo",
    brandId: "cdvi",
    title: "CDVI GALEO / 2EASY",
    model: "GALEO",
    kind: "kit",
    keywords: ["galeo", "galeos", "2easy", "videoportero"],
    hint: "Videoportero 2 hilos. Monitor, placa y esquema de bus.",
  },
  {
    id: "cdvi-tx26",
    brandId: "cdvi",
    title: "Mandos CDVI TX26 / T Series",
    model: "TX26",
    kind: "receptor",
    keywords: ["tx26", "t series", "s3tr2641", "mando", "emisor"],
    hint: "Emisores rolling code y receptores. Memorización y frecuencias.",
  },
  {
    id: "cdvi-solids",
    brandId: "cdvi",
    title: "CDVI SOLIDs / electroimanes",
    model: "SOLIDs",
    kind: "kit",
    keywords: ["solids", "electroiman", "cerradero", "ventosa"],
    hint: "Cerraderos y electroimanes. Esquema 12/24 V y contacto de puerta.",
  },
  {
    id: "visiotech-catalogo",
    brandId: "visiotech",
    title: "Fichas Visiotech (Safire / Nivian / X-Security)",
    model: "Visiotech",
    kind: "manual",
    keywords: [
      "visiotech",
      "safire",
      "nivian",
      "x-security",
      "xsecurity",
      "ficha tecnica",
      "cctv",
    ],
    hint: "Buscar ficha, manual y firmware en visiotechsecurity.com y el soporte técnico.",
  },
  {
    id: "safire-videoportero",
    brandId: "safire",
    title: "Safire videoportero IP / 2 hilos",
    model: "SF-VI",
    kind: "kit",
    keywords: [
      "sf-vi",
      "videoportero",
      "2 hilos",
      "2hilos",
      "monitor",
      "placa calle",
    ],
    hint: "Activación de dispositivos, bus 2 hilos e integración con CCTV Safire.",
  },
  {
    id: "safire-ac",
    brandId: "safire",
    title: "Safire Control Center AC",
    model: "SF-AC",
    kind: "central",
    keywords: [
      "sf-ac",
      "control center",
      "control de acceso",
      "facial",
      "huella",
      "terminal",
    ],
    hint: "Terminales de acceso y software AC. Esquema de cerradero y red.",
  },
  {
    id: "nivian-videoportero",
    brandId: "nivian",
    title: "Nivian videoportero",
    model: "Nivian",
    kind: "kit",
    keywords: ["nivian", "videoportero", "monitor", "placa"],
    hint: "Videoporteros Nivian distribuidos por Visiotech. Manual de instalación.",
  },
  {
    id: "hormann-supramatic",
    brandId: "hormann",
    title: "Hörmann Supramatic / Promatic",
    model: "Supramatic",
    kind: "kit",
    keywords: ["supramatic", "promatic", "hsb", "e4", "bisecur"],
    hint: "Techos seccionales. Programación BiSecur.",
  },
  {
    id: "roger-brushless",
    brandId: "roger",
    title: "Roger Brushless BH / H",
    model: "Brushless",
    kind: "kit",
    keywords: ["roger", "brushless", "bh30", "ctrl"],
    hint: "Motores sin escobillas. Digital 193.",
  },
  {
    id: "dea-ghost",
    brandId: "dea",
    title: "DEA Ghost / Livi",
    model: "Ghost",
    kind: "kit",
    keywords: ["ghost", "livi", "net", "dea"],
    hint: "Corredera y batiente. Central NET.",
  },
];

export const KIND_LABEL: Record<DocKind, string> = {
  esquema: "Esquema",
  manual: "Manual",
  receptor: "Receptor / mando",
  central: "Central / placa",
  kit: "Kit / motor",
};
